/**
 * Real Cribl Source connector types confirmed exempt from ingest license metering — their bytes
 * never count toward the org's daily quota. Used to filter the Daily Ingest panel's own per-source
 * breakdown down to billable Sources only (`api/licenses.ts`'s `fetchSourceBreakdown`) — Signal
 * Path and Flow Explorer deliberately do **not** read this list: those views track what's actually
 * happening to the data (a real Source is still a real, wired-up part of the pipeline regardless of
 * whether Cribl bills for its bytes), not license-relevant volume, so excluding an exempt Source
 * from them would hide a real, existing part of the topology.
 *
 * Confirmed directly against Cribl's own documentation (not just inferred):
 * - `docs.cribl.io/billing-licensing/on-prem-licensing/`: *"Data generated by Datagens does not
 *   count against your ingestion quota"* and *"Data generated by Cribl Internal Sources does not
 *   count against your ingestion quota."*
 * - `docs.cribl.io/stream/sources-cribl-internal/`: names exactly two Cribl Internal Source types —
 *   **CriblLogs** and **CriblMetrics** — an exact match to this app's own real `cribl`/
 *   `criblmetrics` connector types.
 *
 * Also confirmed live against a real test org: `/system/licenses/usage`'s own
 * `exemptedLicenseInBytes` field tracked `inBytes` almost exactly (99+%) on every day that org's
 * traffic was Datagen-dominated, and dropped near zero on days without.
 *
 * **Deliberately excludes `cribl_http`/`cribl_tcp`.** The on-prem licensing doc also exempts data
 * moving between Cribl's own Workers via these two connector types, but only in a genuine hybrid
 * Stream-Cloud + Edge deployment's own internal relay — the same connector type is equally valid
 * for real, billable external ingest, and there's no way to tell the two apart from the source's
 * own `type` alone. Treating every `cribl_http`/`cribl_tcp` Source as exempt would risk silently
 * undercounting real customer traffic; left out rather than guessed.
 */
export const LICENSE_EXEMPT_SOURCE_TYPES: ReadonlySet<string> = new Set(['datagen', 'cribl', 'criblmetrics']);
